service: audit-log-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8
  region: eu-central-1
  stage: stage

package:
  artifact: target/java-basic-1.0-SNAPSHOT.jar

functions:
  getInt:
    handler: example.Handler
    events:
      - http:
          path: test/int
          method: post
  getWeather:
    handler: HandlerWeatherData
    events:
      - http:
          path: test/weather
          method: post        
